### ISSUE TITLE
NSMenu issue

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/FZUIKit#1]
Did not use any code from this library, just linked to this library, and the rounded corners of the Menu disappeared.
<img width="731" alt="iShot_2024-03-19_21 05 30" src="https://github.com/flocked/FZUIKit/assets/61279231/3c5a52aa-420f-4509-8cc9-6f3dbcf7dfdf">

**Comment by Mx-Iris** [comment]
This is example code
[NSMenuIssue.zip](https://github.com/flocked/FZUIKit/files/14650931/NSMenuIssue.zip)

**Comment by flocked** [comment]
It seems importing FZUIkit turns the menus of an app to have no rounded corners. Even when no code of FZUIKit is used. Any idea why? It isn't about the menu provider code. I copied that code to a separate project and get rounded corners.

**Comment by Mx-Iris** [comment]
@flocked After a series of investigations and checks, I found that the modifications in this  [commit](https://github.com/flocked/FZUIKit/commit/9cd0198cdfcc5f373aec6203b933b211cd27f20a) caused the disappearance of the Menu's rounded corners. It is speculated that there might be properties with similar names within Apple's internal classes, and exposing them to objc could have overridden the original implementation.

**Comment by flocked** [comment]
Thanks! This indeed fixed the error! I took a look at the underlying NSView code and Apple already is using the property `_cornerRadius`. So my code somehow overwrote their code (which should normally not be the case).
