### ISSUE TITLE
Considering porting UIKit's UIInteraction interface and classes?

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/FZUIKit#2]
I think UIInteraction is a very good protocol, it is a pity that there is no corresponding NSInteraction on AppKit, I think that the functions such as drag and drop will be encapsulated into NSDropInteraction, NSDragInteraction will be easier to use!

**Comment by Mx-Iris** [comment]
I have a lot of UIKit porting ideas, and it's nice to find someone here who is still writing libraries for AppKit!

**Comment by flocked** [comment]
I was also thinking about porting it, but it's a lot of work.

If you want to discuss your ideas for porting UIKit, you can contact me via my email address (see my GitHub profile).
