### ISSUE TITLE
NSListContentView's updateTableRowHeight method is time-consuming!

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/FZUIKit#3]
<img width="827" alt="iShot_2024-08-07_20 23 36" src="https://github.com/user-attachments/assets/1816084d-b131-4fc2-a114-5bc5de04c5ce">

Is it possible to cache the calculated height, or be able to specify the height of the tableview instead of using the autoheight

**Comment by flocked** [comment]
I updated the code to cache the calculated fitting heights. It also only calculates the height, if the frame height increases.

Btw. you posted this issues at the wrong repository. Use [AdvancedCollectionTableView](https://github.com/flocked/AdvancedCollectionTableView)

**Comment by flocked** [comment]
I found a solution to skip calculating the row height entirely.

The problem was that table view row views come with some autoresizingmask. By disabling `translatesAutoresizingMaskIntoConstraints` the row height automatically updates.
